# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logres', '0002_user_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='course',
        ),
    ]
